"""Initial migration.

Revision ID: 65915b2bc336
Revises: 
Create Date: 2024-07-05 17:28:14.334472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65915b2bc336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConvenienceStoreInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storename', sa.String(length=32), nullable=True),
    sa.Column('storerow', sa.Integer(), nullable=True),
    sa.Column('storecol', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ConvenienceStoreMap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storeinfoid', sa.Integer(), nullable=True),
    sa.Column('storex', sa.Integer(), nullable=True),
    sa.Column('storey', sa.Integer(), nullable=True),
    sa.Column('storestate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['storeinfoid'], ['ConvenienceStoreInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ConvenienceStoreMap')
    op.drop_table('ConvenienceStoreInfo')
    # ### end Alembic commands ###
